/**
 * One-time script: bakes the real JD .docx files in seed/jds/ into versioned
 * TypeScript string constants under src/lib/jd/. Run again any time the JD
 * files change: `npm run seed:jd`.
 */
import fs from "node:fs/promises";
import path from "node:path";
import mammoth from "mammoth";

const JDS_DIR = path.join(process.cwd(), "seed", "jds");
const OUT_DIR = path.join(process.cwd(), "src", "lib", "jd");

const JOBS: { file: string; role: "pm" | "spm"; roleTitle: string }[] = [
  { file: "pm.docx", role: "pm", roleTitle: "Product Manager" },
  { file: "spm.docx", role: "spm", roleTitle: "Senior Product Manager" },
];

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });

  for (const job of JOBS) {
    const filePath = path.join(JDS_DIR, job.file);
    const buffer = await fs.readFile(filePath);
    const { value: text } = await mammoth.extractRawText({ buffer });
    const trimmed = text.trim();

    const contents = `// AUTO-GENERATED by scripts/extract-jd-text.ts from seed/jds/${job.file}.
// Do not hand-edit — re-run \`npm run seed:jd\` after changing the source .docx.

export const ${job.role.toUpperCase()}_JD_TEXT = ${JSON.stringify(trimmed)};
export const ${job.role.toUpperCase()}_JD_ROLE_TITLE = ${JSON.stringify(job.roleTitle)};
export const ${job.role.toUpperCase()}_JD_SOURCE_FILE = ${JSON.stringify(`seed/jds/${job.file}`)};
`;

    const outPath = path.join(OUT_DIR, `${job.role}.ts`);
    await fs.writeFile(outPath, contents, "utf-8");
    console.log(`Wrote ${path.relative(process.cwd(), outPath)} (${trimmed.length} chars)`);
  }
}

main().catch((err) => {
  console.error("extract-jd-text failed:", err);
  process.exit(1);
});
